const layoutNew = [
  {
    name: '两面',
    quickBet: false,
    id: 42,
    items: [
      {
        type: 'normal_grid',
        title: [
          {name: '号码', type: 'label', width: '25%'},
          {name: '赔率', type: 'odds', width: '25%'},
          {name: '金额', type: 'money', width: '50%'}
        ],
        hideTitle: false,
        cols: 4,
        cells: [
          {number: '01',label: '特单'},
          {number: '02',label: '特双'},
          {number: '03',label: '特大'},
          {number: '04',label: '特小'},
          {number: '05',label: '特合单'},
          {number: '06',label: '特合双'},
          {number: '07',label: '特合大'},
          {number: '08',label: '特合小'},
          {number: '09',label: '特尾大'},
          {number: '10',label: '特尾小'},
          {number: '11',label: '特天肖'},
          {number: '12',label: '特地肖'},
          {number: '13',label: '特前肖'},
          {number: '14',label: '特后肖'},
          {number: '15',label: '特家肖'},
          {number: '16',label: '特野肖'},
          {number: '17',label: '总单'},
          {number: '18',label: '总双'},
          {number: '19',label: '总大'},
          {number: '20',label: '总小'}
        ]
      },
    ]
  },
  {
    name: '特码AB',
    id: 43,
    type: 'tebiehao',
    quickBet: true,
    items:[
        {
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        },
    ]
  },
  {
    name: '正码',
    id: 44,
    type: 'zhengma',
    quickBet: true,
    items:[
      {
        type: 'normal_grid',
        title: [
          {name: '号码', type: 'number', width: '25%'},
          {name: '赔率', type: 'odds', width: '25%'},
          {name: '金额', type: 'money', width: '50%'}
        ],
        hideTitle: false,
        cols: 5,
        cells: [
          {number: '01', name: 'NA01'},
          {number: '11', name: 'NA11'},
          {number: '21', name: 'NA21'},
          {number: '31', name: 'NA31'},
          {number: '41', name: 'NA41'},
          {number: '02', name: 'NA02'},
          {number: '12', name: 'NA12'},
          {number: '22', name: 'NA22'},
          {number: '32', name: 'NA32'},
          {number: '42', name: 'NA42'},
          {number: '03', name: 'NA03'},
          {number: '13', name: 'NA13'},
          {number: '23', name: 'NA23'},
          {number: '33', name: 'NA33'},
          {number: '43', name: 'NA43'},
          {number: '04', name: 'NA04'},
          {number: '14', name: 'NA14'},
          {number: '24', name: 'NA24'},
          {number: '34', name: 'NA34'},
          {number: '44', name: 'NA44'},
          {number: '05', name: 'NA05'},
          {number: '15', name: 'NA15'},
          {number: '25', name: 'NA25'},
          {number: '35', name: 'NA35'},
          {number: '45', name: 'NA45'},
          {number: '06', name: 'NA06'},
          {number: '16', name: 'NA16'},
          {number: '26', name: 'NA26'},
          {number: '36', name: 'NA36'},
          {number: '46', name: 'NA46'},
          {number: '07', name: 'NA07'},
          {number: '17', name: 'NA17'},
          {number: '27', name: 'NA27'},
          {number: '37', name: 'NA37'},
          {number: '47', name: 'NA47'},
          {number: '08', name: 'NA08'},
          {number: '18', name: 'NA18'},
          {number: '28', name: 'NA28'},
          {number: '38', name: 'NA38'},
          {number: '48', name: 'NA48'},
          {number: '09', name: 'NA09'},
          {number: '19', name: 'NA19'},
          {number: '29', name: 'NA29'},
          {number: '39', name: 'NA39'},
          {number: '49', name: 'NA49'},
          {number: '10', name: 'NA10'},
          {number: '20', name: 'NA20'},
          {number: '30', name: 'NA30'},
          {number: '40', name: 'NA40'},
          {number: ''}
        ]
      }
    ]
  },
  {
    name: '正码特',
    id: 45,
    type: 'zhengmate',
    quickBet: true,
    tabs: [
      {
        name: '正一特',
        type: 'N1',
        quickBet: true,
        defaultSelected: true,
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01', odds: 46, name: 'N101'},
            {number: '11', odds: 46, name: 'N111'},
            {number: '21', odds: 46, name: 'N121'},
            {number: '31', odds: 46, name: 'N131'},
            {number: '41', odds: 46, name: 'N141'},
            {number: '02', odds: 46, name: 'N102'},
            {number: '12', odds: 46, name: 'N112'},
            {number: '22', odds: 46, name: 'N122'},
            {number: '32', odds: 46, name: 'N132'},
            {number: '42', odds: 46, name: 'N142'},
            {number: '03', odds: 46, name: 'N103'},
            {number: '13', odds: 46, name: 'N113'},
            {number: '23', odds: 46, name: 'N123'},
            {number: '33', odds: 46, name: 'N133'},
            {number: '43', odds: 46, name: 'N143'},
            {number: '04', odds: 46, name: 'N104'},
            {number: '14', odds: 46, name: 'N114'},
            {number: '24', odds: 46, name: 'N124'},
            {number: '34', odds: 46, name: 'N134'},
            {number: '44', odds: 46, name: 'N144'},
            {number: '05', odds: 46, name: 'N105'},
            {number: '15', odds: 46, name: 'N115'},
            {number: '25', odds: 46, name: 'N125'},
            {number: '35', odds: 46, name: 'N135'},
            {number: '45', odds: 46, name: 'N145'},
            {number: '06', odds: 46, name: 'N106'},
            {number: '16', odds: 46, name: 'N116'},
            {number: '26', odds: 46, name: 'N126'},
            {number: '36', odds: 46, name: 'N136'},
            {number: '46', odds: 46, name: 'N146'},
            {number: '07', odds: 46, name: 'N107'},
            {number: '17', odds: 46, name: 'N117'},
            {number: '27', odds: 46, name: 'N127'},
            {number: '37', odds: 46, name: 'N137'},
            {number: '47', odds: 46, name: 'N147'},
            {number: '08', odds: 46, name: 'N108'},
            {number: '18', odds: 46, name: 'N118'},
            {number: '28', odds: 46, name: 'N128'},
            {number: '38', odds: 46, name: 'N138'},
            {number: '48', odds: 46, name: 'N148'},
            {number: '09', odds: 46, name: 'N109'},
            {number: '19', odds: 46, name: 'N119'},
            {number: '29', odds: 46, name: 'N129'},
            {number: '39', odds: 46, name: 'N139'},
            {number: '49', odds: 46, name: 'N149'},
            {number: '10', odds: 46, name: 'N110'},
            {number: '20', odds: 46, name: 'N120'},
            {number: '30', odds: 46, name: 'N130'},
            {number: '40', odds: 46, name: 'N140'},
            {number: ''}
          ]
        }]
      }, //defaultSelected 待优化
      {
        name: '正二特',
        type: 'N2',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01', odds: 46, name: 'N201'},
            {number: '11', odds: 46, name: 'N211'},
            {number: '21', odds: 46, name: 'N221'},
            {number: '31', odds: 46, name: 'N231'},
            {number: '41', odds: 46, name: 'N241'},
            {number: '02', odds: 46, name: 'N202'},
            {number: '12', odds: 46, name: 'N212'},
            {number: '22', odds: 46, name: 'N222'},
            {number: '32', odds: 46, name: 'N232'},
            {number: '42', odds: 46, name: 'N242'},
            {number: '03', odds: 46, name: 'N203'},
            {number: '13', odds: 46, name: 'N213'},
            {number: '23', odds: 46, name: 'N223'},
            {number: '33', odds: 46, name: 'N233'},
            {number: '43', odds: 46, name: 'N243'},
            {number: '04', odds: 46, name: 'N204'},
            {number: '14', odds: 46, name: 'N214'},
            {number: '24', odds: 46, name: 'N224'},
            {number: '34', odds: 46, name: 'N234'},
            {number: '44', odds: 46, name: 'N244'},
            {number: '05', odds: 46, name: 'N205'},
            {number: '15', odds: 46, name: 'N215'},
            {number: '25', odds: 46, name: 'N225'},
            {number: '35', odds: 46, name: 'N235'},
            {number: '45', odds: 46, name: 'N245'},
            {number: '06', odds: 46, name: 'N206'},
            {number: '16', odds: 46, name: 'N216'},
            {number: '26', odds: 46, name: 'N226'},
            {number: '36', odds: 46, name: 'N236'},
            {number: '46', odds: 46, name: 'N246'},
            {number: '07', odds: 46, name: 'N207'},
            {number: '17', odds: 46, name: 'N217'},
            {number: '27', odds: 46, name: 'N227'},
            {number: '37', odds: 46, name: 'N237'},
            {number: '47', odds: 46, name: 'N247'},
            {number: '08', odds: 46, name: 'N208'},
            {number: '18', odds: 46, name: 'N218'},
            {number: '28', odds: 46, name: 'N228'},
            {number: '38', odds: 46, name: 'N238'},
            {number: '48', odds: 46, name: 'N248'},
            {number: '09', odds: 46, name: 'N209'},
            {number: '19', odds: 46, name: 'N219'},
            {number: '29', odds: 46, name: 'N229'},
            {number: '39', odds: 46, name: 'N239'},
            {number: '49', odds: 46, name: 'N249'},
            {number: '10', odds: 46, name: 'N210'},
            {number: '20', odds: 46, name: 'N220'},
            {number: '30', odds: 46, name: 'N230'},
            {number: '40', odds: 46, name: 'N240'},
            {number: ''}
          ]
        }]
      },
      {
        name: '正三特',
        type: 'N3',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01', odds: 46, name: 'N301'},
            {number: '11', odds: 46, name: 'N311'},
            {number: '21', odds: 46, name: 'N321'},
            {number: '31', odds: 46, name: 'N331'},
            {number: '41', odds: 46, name: 'N341'},
            {number: '02', odds: 46, name: 'N302'},
            {number: '12', odds: 46, name: 'N312'},
            {number: '22', odds: 46, name: 'N322'},
            {number: '32', odds: 46, name: 'N332'},
            {number: '42', odds: 46, name: 'N342'},
            {number: '03', odds: 46, name: 'N303'},
            {number: '13', odds: 46, name: 'N313'},
            {number: '23', odds: 46, name: 'N323'},
            {number: '33', odds: 46, name: 'N333'},
            {number: '43', odds: 46, name: 'N343'},
            {number: '04', odds: 46, name: 'N304'},
            {number: '14', odds: 46, name: 'N314'},
            {number: '24', odds: 46, name: 'N324'},
            {number: '34', odds: 46, name: 'N334'},
            {number: '44', odds: 46, name: 'N344'},
            {number: '05', odds: 46, name: 'N305'},
            {number: '15', odds: 46, name: 'N315'},
            {number: '25', odds: 46, name: 'N325'},
            {number: '35', odds: 46, name: 'N335'},
            {number: '45', odds: 46, name: 'N345'},
            {number: '06', odds: 46, name: 'N306'},
            {number: '16', odds: 46, name: 'N316'},
            {number: '26', odds: 46, name: 'N326'},
            {number: '36', odds: 46, name: 'N336'},
            {number: '46', odds: 46, name: 'N346'},
            {number: '07', odds: 46, name: 'N307'},
            {number: '17', odds: 46, name: 'N317'},
            {number: '27', odds: 46, name: 'N327'},
            {number: '37', odds: 46, name: 'N337'},
            {number: '47', odds: 46, name: 'N347'},
            {number: '08', odds: 46, name: 'N308'},
            {number: '18', odds: 46, name: 'N318'},
            {number: '28', odds: 46, name: 'N328'},
            {number: '38', odds: 46, name: 'N338'},
            {number: '48', odds: 46, name: 'N348'},
            {number: '09', odds: 46, name: 'N309'},
            {number: '19', odds: 46, name: 'N319'},
            {number: '29', odds: 46, name: 'N329'},
            {number: '39', odds: 46, name: 'N339'},
            {number: '49', odds: 46, name: 'N349'},
            {number: '10', odds: 46, name: 'N310'},
            {number: '20', odds: 46, name: 'N320'},
            {number: '30', odds: 46, name: 'N330'},
            {number: '40', odds: 46, name: 'N340'},
            {number: ''}
          ]
        }]
      },
      {
        name: '正四特',
        type: 'N4',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01', odds: 46, name: 'N401'},
            {number: '11', odds: 46, name: 'N411'},
            {number: '21', odds: 46, name: 'N421'},
            {number: '31', odds: 46, name: 'N431'},
            {number: '41', odds: 46, name: 'N441'},
            {number: '02', odds: 46, name: 'N402'},
            {number: '12', odds: 46, name: 'N412'},
            {number: '22', odds: 46, name: 'N422'},
            {number: '32', odds: 46, name: 'N432'},
            {number: '42', odds: 46, name: 'N442'},
            {number: '03', odds: 46, name: 'N403'},
            {number: '13', odds: 46, name: 'N413'},
            {number: '23', odds: 46, name: 'N423'},
            {number: '33', odds: 46, name: 'N433'},
            {number: '43', odds: 46, name: 'N443'},
            {number: '04', odds: 46, name: 'N404'},
            {number: '14', odds: 46, name: 'N414'},
            {number: '24', odds: 46, name: 'N424'},
            {number: '34', odds: 46, name: 'N434'},
            {number: '44', odds: 46, name: 'N444'},
            {number: '05', odds: 46, name: 'N405'},
            {number: '15', odds: 46, name: 'N415'},
            {number: '25', odds: 46, name: 'N425'},
            {number: '35', odds: 46, name: 'N435'},
            {number: '45', odds: 46, name: 'N445'},
            {number: '06', odds: 46, name: 'N406'},
            {number: '16', odds: 46, name: 'N416'},
            {number: '26', odds: 46, name: 'N426'},
            {number: '36', odds: 46, name: 'N436'},
            {number: '46', odds: 46, name: 'N446'},
            {number: '07', odds: 46, name: 'N407'},
            {number: '17', odds: 46, name: 'N417'},
            {number: '27', odds: 46, name: 'N427'},
            {number: '37', odds: 46, name: 'N437'},
            {number: '47', odds: 46, name: 'N447'},
            {number: '08', odds: 46, name: 'N408'},
            {number: '18', odds: 46, name: 'N418'},
            {number: '28', odds: 46, name: 'N428'},
            {number: '38', odds: 46, name: 'N438'},
            {number: '48', odds: 46, name: 'N448'},
            {number: '09', odds: 46, name: 'N409'},
            {number: '19', odds: 46, name: 'N419'},
            {number: '29', odds: 46, name: 'N429'},
            {number: '39', odds: 46, name: 'N439'},
            {number: '49', odds: 46, name: 'N449'},
            {number: '10', odds: 46, name: 'N410'},
            {number: '20', odds: 46, name: 'N420'},
            {number: '30', odds: 46, name: 'N430'},
            {number: '40', odds: 46, name: 'N440'},
            {number: ''}
          ]
        }]
      },
      {
        name: '正五特',
        type: 'N5',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01', odds: 46, name: 'N501'},
            {number: '11', odds: 46, name: 'N511'},
            {number: '21', odds: 46, name: 'N521'},
            {number: '31', odds: 46, name: 'N531'},
            {number: '41', odds: 46, name: 'N541'},
            {number: '02', odds: 46, name: 'N502'},
            {number: '12', odds: 46, name: 'N512'},
            {number: '22', odds: 46, name: 'N522'},
            {number: '32', odds: 46, name: 'N532'},
            {number: '42', odds: 46, name: 'N542'},
            {number: '03', odds: 46, name: 'N503'},
            {number: '13', odds: 46, name: 'N513'},
            {number: '23', odds: 46, name: 'N523'},
            {number: '33', odds: 46, name: 'N533'},
            {number: '43', odds: 46, name: 'N543'},
            {number: '04', odds: 46, name: 'N504'},
            {number: '14', odds: 46, name: 'N514'},
            {number: '24', odds: 46, name: 'N524'},
            {number: '34', odds: 46, name: 'N534'},
            {number: '44', odds: 46, name: 'N544'},
            {number: '05', odds: 46, name: 'N505'},
            {number: '15', odds: 46, name: 'N515'},
            {number: '25', odds: 46, name: 'N525'},
            {number: '35', odds: 46, name: 'N535'},
            {number: '45', odds: 46, name: 'N545'},
            {number: '06', odds: 46, name: 'N506'},
            {number: '16', odds: 46, name: 'N516'},
            {number: '26', odds: 46, name: 'N526'},
            {number: '36', odds: 46, name: 'N536'},
            {number: '46', odds: 46, name: 'N546'},
            {number: '07', odds: 46, name: 'N507'},
            {number: '17', odds: 46, name: 'N517'},
            {number: '27', odds: 46, name: 'N527'},
            {number: '37', odds: 46, name: 'N537'},
            {number: '47', odds: 46, name: 'N547'},
            {number: '08', odds: 46, name: 'N508'},
            {number: '18', odds: 46, name: 'N518'},
            {number: '28', odds: 46, name: 'N528'},
            {number: '38', odds: 46, name: 'N538'},
            {number: '48', odds: 46, name: 'N548'},
            {number: '09', odds: 46, name: 'N509'},
            {number: '19', odds: 46, name: 'N519'},
            {number: '29', odds: 46, name: 'N529'},
            {number: '39', odds: 46, name: 'N539'},
            {number: '49', odds: 46, name: 'N549'},
            {number: '10', odds: 46, name: 'N510'},
            {number: '20', odds: 46, name: 'N520'},
            {number: '30', odds: 46, name: 'N530'},
            {number: '40', odds: 46, name: 'N540'},
            {number: ''}
          ]
        }]
      },
      {
        name: '正六特',
        type: 'N6',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '25%'},
            {name: '赔率', type: 'odds', width: '25%'},
            {name: '金额', type: 'money', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01', odds: 46, name: 'N601'},
            {number: '11', odds: 46, name: 'N611'},
            {number: '21', odds: 46, name: 'N621'},
            {number: '31', odds: 46, name: 'N631'},
            {number: '41', odds: 46, name: 'N641'},
            {number: '02', odds: 46, name: 'N602'},
            {number: '12', odds: 46, name: 'N612'},
            {number: '22', odds: 46, name: 'N622'},
            {number: '32', odds: 46, name: 'N632'},
            {number: '42', odds: 46, name: 'N642'},
            {number: '03', odds: 46, name: 'N603'},
            {number: '13', odds: 46, name: 'N613'},
            {number: '23', odds: 46, name: 'N623'},
            {number: '33', odds: 46, name: 'N633'},
            {number: '43', odds: 46, name: 'N643'},
            {number: '04', odds: 46, name: 'N604'},
            {number: '14', odds: 46, name: 'N614'},
            {number: '24', odds: 46, name: 'N624'},
            {number: '34', odds: 46, name: 'N634'},
            {number: '44', odds: 46, name: 'N644'},
            {number: '05', odds: 46, name: 'N605'},
            {number: '15', odds: 46, name: 'N615'},
            {number: '25', odds: 46, name: 'N625'},
            {number: '35', odds: 46, name: 'N635'},
            {number: '45', odds: 46, name: 'N645'},
            {number: '06', odds: 46, name: 'N606'},
            {number: '16', odds: 46, name: 'N616'},
            {number: '26', odds: 46, name: 'N626'},
            {number: '36', odds: 46, name: 'N636'},
            {number: '46', odds: 46, name: 'N646'},
            {number: '07', odds: 46, name: 'N607'},
            {number: '17', odds: 46, name: 'N617'},
            {number: '27', odds: 46, name: 'N627'},
            {number: '37', odds: 46, name: 'N637'},
            {number: '47', odds: 46, name: 'N647'},
            {number: '08', odds: 46, name: 'N608'},
            {number: '18', odds: 46, name: 'N618'},
            {number: '28', odds: 46, name: 'N628'},
            {number: '38', odds: 46, name: 'N638'},
            {number: '48', odds: 46, name: 'N648'},
            {number: '09', odds: 46, name: 'N609'},
            {number: '19', odds: 46, name: 'N619'},
            {number: '29', odds: 46, name: 'N629'},
            {number: '39', odds: 46, name: 'N639'},
            {number: '49', odds: 46, name: 'N649'},
            {number: '10', odds: 46, name: 'N610'},
            {number: '20', odds: 46, name: 'N620'},
            {number: '30', odds: 46, name: 'N630'},
            {number: '40', odds: 46, name: 'N640'},
            {number: ''}
          ]
        }]
      }
    ]
  },
  {
    name: '正码 1-6',
    id: 46,
    quickBet: false,
    items: [
      {
        type: 'normal_grid',
        totleTitle: ['正码一', '正码二', '正码三', '正码四', '正码五', '正码六'],
        title: [
          {name: '赔率', type: 'odds', width: '30%'},
          {name: '金额', type: 'money', width: '70%'}
        ],
        TDTitle: ['号码', '单', '双', '大', '小', '合单', '合双', '合大', '合小', '尾大', '尾小', '红波', '绿波', '蓝波'],
        cols: 6,
        cells: [
          {number: '01'},
          {number: '14'},
          {number: '27'},
          {number: '40'},
          {number: '53'},
          {number: '66'},
          {number: '02'},
          {number: '15'},
          {number: '28'},
          {number: '41'},
          {number: '54'},
          {number: '67'},
          {number: '03'},
          {number: '16'},
          {number: '29'},
          {number: '42'},
          {number: '55'},
          {number: '68'},
          {number: '04'},
          {number: '17'},
          {number: '30'},
          {number: '43'},
          {number: '56'},
          {number: '69'},
          {number: '05'},
          {number: '18'},
          {number: '31'},
          {number: '44'},
          {number: '57'},
          {number: '70'},
          {number: '06'},
          {number: '19'},
          {number: '32'},
          {number: '45'},
          {number: '58'},
          {number: '71'},
          {number: '07'},
          {number: '20'},
          {number: '33'},
          {number: '46'},
          {number: '59'},
          {number: '72'},
          {number: '08'},
          {number: '21'},
          {number: '34'},
          {number: '47'},
          {number: '60'},
          {number: '73'},
          {number: '09'},
          {number: '22'},
          {number: '35'},
          {number: '48'},
          {number: '61'},
          {number: '74'},
          {number: '10'},
          {number: '23'},
          {number: '36'},
          {number: '49'},
          {number: '62'},
          {number: '75'},
          {number: '11'},
          {number: '24'},
          {number: '37'},
          {number: '50'},
          {number: '63'},
          {number: '76'},
          {number: '12'},
          {number: '25'},
          {number: '38'},
          {number: '51'},
          {number: '64'},
          {number: '77'},
          {number: '13'},
          {number: '26'},
          {number: '39'},
          {number: '52'},
          {number: '65'},
          {number: '78'},
        ]
      }
    ]
  },
  {
    name: '正码过关',
    quickBet: false,
    id: 47,
    type: 'zhengmaguoguan',
    items: [
      {
        type: 'normal_grid',
        totleTitle: ['正码一', '正码二', '正码三', '正码四', '正码五', '正码六'],
        title: [
          {name: '赔率', type: 'odds_radio', width: '50%'},
          {name: '选择', type: 'radio', width: '50%'}
        ],
        TDTitle: ['号码', '单', '双', '大', '小', '合单', '合双', '合大', '合小', '尾大', '尾小', '红', '绿', '蓝'],
        cols: 6,
        cells: [
          {number: '1'},
          {number: '14'},
          {number: '27'},
          {number: '40'},
          {number: '53'},
          {number: '66'},
          {number: '2'},
          {number: '15'},
          {number: '28'},
          {number: '41'},
          {number: '54'},
          {number: '67'},
          {number: '3'},
          {number: '16'},
          {number: '29'},
          {number: '42'},
          {number: '55'},
          {number: '68'},
          {number: '4'},
          {number: '17'},
          {number: '30'},
          {number: '43'},
          {number: '56'},
          {number: '69'},
          {number: '5'},
          {number: '18'},
          {number: '31'},
          {number: '44'},
          {number: '57'},
          {number: '70'},
          {number: '6'},
          {number: '19'},
          {number: '32'},
          {number: '45'},
          {number: '58'},
          {number: '71'},
          {number: '7'},
          {number: '20'},
          {number: '33'},
          {number: '46'},
          {number: '59'},
          {number: '72'},
          {number: '8'},
          {number: '21'},
          {number: '34'},
          {number: '47'},
          {number: '60'},
          {number: '73'},
          {number: '9'},
          {number: '22'},
          {number: '35'},
          {number: '48'},
          {number: '61'},
          {number: '74'},
          {number: '10'},
          {number: '23'},
          {number: '36'},
          {number: '49'},
          {number: '62'},
          {number: '75'},
          {number: '11'},
          {number: '24'},
          {number: '37'},
          {number: '50'},
          {number: '63'},
          {number: '76'},
          {number: '12'},
          {number: '25'},
          {number: '38'},
          {number: '51'},
          {number: '64'},
          {number: '77'},
          {number: '13'},
          {number: '26'},
          {number: '39'},
          {number: '52'},
          {number: '65'},
          {number: '78'},
        ]
      }
    ]
  },
  {
    name: '连码',
    id: 48,
    type: 'lianma',
    tabs: [
      {
        name: '四全中',
        type: 'CH_4',
        quickBet: false,
        defaultSelected: true,
        subTabs: ['正/副号', '肖串尾数', '交叉碰', '胆拖', '胆拖色波', '胆拖生肖'],
        series: 4
      },
      {
        name: '三全中',
        type: 'CH_3',
        subTabs: ['正/副号', '肖串尾数', '交叉碰', '胆拖', '胆拖色波', '胆拖生肖'],
        series: 3
      },
      {
        name: '三中二',
        type: 'CH_32',
        subTabs: ['正/副号', '肖串尾数', '交叉碰', '胆拖', '胆拖色波', '胆拖生肖'],
        series: 3
      },
      {
        name: '二全中',
        type: 'CH_2',
        subTabs: ['正/副号', '生肖对碰', '尾数对碰', '肖串尾数', '交叉碰', '胆拖', '胆拖色波', '胆拖生肖'],
        series: 2
      },
      {
        name: '二中特',
        type: 'CH_2S',
        subTabs: ['正/副号', '生肖对碰', '尾数对碰', '肖串尾数', '交叉碰', '胆拖', '胆拖色波', '胆拖生肖'],
        series: 2
      },
      {
        name: '特串',
        type: 'CH_2SP',
        subTabs: ['正/副号', '生肖对碰', '尾数对碰', '肖串尾数', '交叉碰', '胆拖', '胆拖色波', '胆拖生肖'],
        series: 2
      }
    ]
  },
  {
    name: '连肖连尾',
    quickBet: false,
    id: 49,
    type: 'lianxiao',
    tabs: [
      {
        name: '二肖连',
        quickBet: false,
        type: 'LX2',
        defaultSelected: true,
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'shengXiao', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: 1},
            {number: 2},
            {number: 3},
            {number: 4},
            {number: 5},
            {number: 6},
            {number: 7},
            {number: 8},
            {number: 9},
            {number: 10},
            {number: 11},
            {number: 12},
          ]
        }]
      },
      {
        name: '三肖连',
        type: 'LX3',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'shengXiao', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: 1},
            {number: 2},
            {number: 3},
            {number: 4},
            {number: 5},
            {number: 6},
            {number: 7},
            {number: 8},
            {number: 9},
            {number: 10},
            {number: 11},
            {number: 12},
          ]
        }]
      },
      {
        name: '四肖连',
        type: 'LX4',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'shengXiao', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: 1},
            {number: 2},
            {number: 3},
            {number: 4},
            {number: 5},
            {number: 6},
            {number: 7},
            {number: 8},
            {number: 9},
            {number: 10},
            {number: 11},
            {number: 12},
          ]
        }]
      },
      {
        name: '五肖连',
        type: 'LX5',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'shengXiao', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: 1},
            {number: 2},
            {number: 3},
            {number: 4},
            {number: 5},
            {number: 6},
            {number: 7},
            {number: 8},
            {number: 9},
            {number: 10},
            {number: 11},
            {number: 12},
          ]
        }]
      },
      {
        name: '二连尾',
        type: 'LF2',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '尾数', type: 'checkLabelW', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'weishu', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {name: 0, number: 1},
            {name: 1, number: 2},
            {name: 2, number: 3},
            {name: 3, number: 4},
            {name: 4, number: 5},
            {name: 5, number: 6},
            {name: 6, number: 7},
            {name: 7, number: 8},
            {name: 8, number: 9},
            {name: 9, number: 10},
          ]
        }]
      },
      {
        name: '三连尾',
        type: 'LF3',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '尾数', type: 'checkLabelW', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'weishu', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {name: 0, number: 1},
            {name: 1, number: 2},
            {name: 2, number: 3},
            {name: 3, number: 4},
            {name: 4, number: 5},
            {name: 5, number: 6},
            {name: 6, number: 7},
            {name: 7, number: 8},
            {name: 8, number: 9},
            {name: 9, number: 10},
          ]
        }]
      },
      {
        name: '四连尾',
        type: 'LF4',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '尾数', type: 'checkLabelW', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'weishu', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {name: 0, number: 1},
            {name: 1, number: 2},
            {name: 2, number: 3},
            {name: 3, number: 4},
            {name: 4, number: 5},
            {name: 5, number: 6},
            {name: 6, number: 7},
            {name: 7, number: 8},
            {name: 8, number: 9},
            {name: 9, number: 10},
          ]
        }]
      },
      {
        name: '五连尾',
        type: 'LF5',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '尾数', type: 'checkLabelW', width: '20%'},
            {name: '赔率', type: 'odds', width: '20%'},
            {name: '号码', type: 'weishu', width: '60%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {name: 0, number: 1},
            {name: 1, number: 2},
            {name: 2, number: 3},
            {name: 3, number: 4},
            {name: 4, number: 5},
            {name: 5, number: 6},
            {name: 6, number: 7},
            {name: 7, number: 8},
            {name: 8, number: 9},
            {name: 9, number: 10},
          ]
        }]
      }
    ]
  },
  {
    name: '自选不中',
    quickBet: false,
    id: 50,
    type: 'zixuanbuzhong',
    tabs: [
      {
        name: '五不中',
        type: 'NI5',
        quickBet: false,
        defaultSelected: true,
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '六不中',
        type: 'NI6',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '七不中',
        type: 'NI7',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '八不中',
        type: 'NI8',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
       },
      {
        name: '九不中',
        type: 'NI9',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '十不中',
        type: 'NIA',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '十一不中',
        type: 'NIB',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '十二不中',
        type: 'NIC',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      }
    ]
  },
  {
    name: '生肖',
    quickBet: false,
    id: 51,
    tabs: [
      {
        name: '正肖',
        type: 'NI5',
        quickBet: false,
        defaultSelected: true,
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '生肖', type: 'label', width: '15%'},
              {name: '号码', type: 'shengXiao', width: '45%'},
              {name: '赔率', type: 'odds', width: '15%'},
              {name: '金额', type: 'money', width: '25%'}
            ],
            hideTitle: false,
            cols: 2,
            cells: [
              {label: '鼠', number: '1', shengXiao: '09, 21, 33, 45', name: 'SP_A1'},
              {label: '牛', number: '2', shengXiao: '08, 20, 32, 44', name: 'SP_A2'},
              {label: '虎', number: '3', shengXiao: '07, 19, 31, 43', name: 'SP_A3'},
              {label: '兔', number: '4', shengXiao: '06, 18, 30, 42', name: 'SP_A4'},
              {label: '龙', number: '5', shengXiao: '05, 17, 29, 41', name: 'SP_A5'},
              {label: '蛇', number: '6', shengXiao: '04, 16, 28, 40', name: 'SP_A6'},
              {label: '马', number: '7', shengXiao: '03, 15, 27, 39', name: 'SP_A7'},
              {label: '羊', number: '8', shengXiao: '02, 14, 26, 38', name: 'SP_A8'},
              {label: '猴', number: '9', shengXiao: '01, 13, 25, 37, 49', name: 'SP_A9'},
              {label: '鸡', number: '10', shengXiao: '12, 24, 36, 48', name: 'SP_AA'},
              {label: '狗', number: '11', shengXiao: '11, 23, 35, 47', name: 'SP_AB'},
              {label: '猪', number: '12', shengXiao: '10, 22, 34, 46', name: 'SP_AC'}
            ]
          }
        ]
      },
      {
        name: '特肖',
        type: 'NI6',
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '十二生肖', type: 'label', width: '20%'},
              {name: '号码', type: 'shengXiao', width: '35%'},
              {name: '赔率', type: 'odds', width: '20%'},
              {name: '金额', type: 'money', width: '25%'}
            ],
            hideTitle: false,
            cols: 2,
            cells: [
              {label: '鼠', number: '1', shengXiao: '09, 21, 33, 45', name: 'SP_A1'},
              {label: '牛', number: '2', shengXiao: '08, 20, 32, 44', name: 'SP_A2'},
              {label: '虎', number: '3', shengXiao: '07, 19, 31, 43', name: 'SP_A3'},
              {label: '兔', number: '4', shengXiao: '06, 18, 30, 42', name: 'SP_A4'},
              {label: '龙', number: '5', shengXiao: '05, 17, 29, 41', name: 'SP_A5'},
              {label: '蛇', number: '6', shengXiao: '04, 16, 28, 40', name: 'SP_A6'},
              {label: '马', number: '7', shengXiao: '03, 15, 27, 39', name: 'SP_A7'},
              {label: '羊', number: '8', shengXiao: '02, 14, 26, 38', name: 'SP_A8'},
              {label: '猴', number: '9', shengXiao: '01, 13, 25, 37, 49', name: 'SP_A9'},
              {label: '鸡', number: '10', shengXiao: '12, 24, 36, 48', name: 'SP_AA'},
              {label: '狗', number: '11', shengXiao: '11, 23, 35, 47', name: 'SP_AB'},
              {label: '猪', number: '12', shengXiao: '10, 22, 34, 46', name: 'SP_AC'}
            ]
          }
        ]
      },
      {
        name: '一肖',
        type: 'NI7',
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '十二生肖', type: 'label', width: '20%'},
              {name: '号码', type: 'shengXiao', width: '35%'},
              {name: '赔率', type: 'odds', width: '20%'},
              {name: '金额', type: 'money', width: '25%'}
            ],
            hideTitle: false,
            cols: 2,
            cells: [
              {label: '鼠', number: '1', shengXiao: '09, 21, 33, 45', name: 'SP_A1'},
              {label: '牛', number: '2', shengXiao: '08, 20, 32, 44', name: 'SP_A2'},
              {label: '虎', number: '3', shengXiao: '07, 19, 31, 43', name: 'SP_A3'},
              {label: '兔', number: '4', shengXiao: '06, 18, 30, 42', name: 'SP_A4'},
              {label: '龙', number: '5', shengXiao: '05, 17, 29, 41', name: 'SP_A5'},
              {label: '蛇', number: '6', shengXiao: '04, 16, 28, 40', name: 'SP_A6'},
              {label: '马', number: '7', shengXiao: '03, 15, 27, 39', name: 'SP_A7'},
              {label: '羊', number: '8', shengXiao: '02, 14, 26, 38', name: 'SP_A8'},
              {label: '猴', number: '9', shengXiao: '01, 13, 25, 37, 49', name: 'SP_A9'},
              {label: '鸡', number: '10', shengXiao: '12, 24, 36, 48', name: 'SP_AA'},
              {label: '狗', number: '11', shengXiao: '11, 23, 35, 47', name: 'SP_AB'},
              {label: '猪', number: '12', shengXiao: '10, 22, 34, 46', name: 'SP_AC'}
            ]
          }
        ]
      },
      {
        name: '总肖',
        type: 'NI8',
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '号码', type: 'label', width: '25%'},
              {name: '赔率', type: 'odds', width: '25%'},
              {name: '金额', type: 'money', width: '50%'}
            ],
            hideTitle: true,
            mainTitle: '总肖',
            cols: 2,
            cells: [
              {label: '234肖', number: '1', name: 'TX2'},
              {label: '5肖', number: '2', name: 'TX5'},
              {label: '6肖', number: '3', name: 'TX6'},
              {label: '7肖', number: '4', name: 'TX7'},
              {label: '总肖单', number: '5', name: 'TX_ODD'},
              {label: '总肖双', number: '6', name: 'TX_EVEN'}
            ]
          }
        ]
      }
    ],

  },
  {
    name: '合肖',
    quickBet: false,
    id: 52,
    type: 'hexiao',
    tabs: [
      {
        name: '野兽',
        type: 'YE_SHOU',
        quickBet: false,
        defaultSelected: true,
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '家禽',
        type: 'JIA_QING',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '单',
        type: 'DAN',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '双',
        type: 'SHUANG',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '前肖',
        type: 'QIAN_XIAO',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '后肖',
        type: 'HOU_XIAO',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '天肖',
        type: 'TIAN_XIAO',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
      {
        name: '地肖',
        type: 'DI_XIAO',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '生肖', type: 'checkLabel', width: '30%'},
            {name: '号码', type: 'shengXiao', width: '70%'}
          ],
          hideTitle: false,
          cols: 2,
          cells: [
            {number: '1'},
            {number: '2'},
            {number: '3'},
            {number: '4'},
            {number: '5'},
            {number: '6'},
            {number: '7'},
            {number: '8'},
            {number: '9'},
            {number: '10'},
            {number: '11'},
            {number: '12'},
          ]
        }]
      },
    ]
  },
  {
    name: '色波',
    quickBet: false,
    id: 53,
    tabs: [
        {
          name: '三色波',
          type: 'SB1',
          quickBet: false,
          defaultSelected: true,
          items: [{
            type: 'normal_grid',
            title: [
              {name: '号码', type: 'label', width: '25%'},
              {name: '赔率', type: 'odds', width: '25%'},
              {name: '金额', type: 'money', width: '50%'}
            ],
            hideTitle: true,
            mainTitle: '色波',
            cols: 3,
            cells: [
              {label: '红波', number: '1', name: 'SP_R'},
              {label: '蓝波', number: '2', name: 'SP_B'},
              {label: '绿波', number: '3', name: 'SP_G'}
            ]
          }]
        },
        {
          name: '半波',
          type: 'SB2',
          items: [{
            type: 'normal_grid',
            title: [
              {name: '半波', type: 'label', width: '20%'},
              {name: '赔率', type: 'odds', width: '20%'},
              {name: '金额', type: 'money', width: '25%'},
              {name: '号码', type: 'balls', width: '35%'},
            ],
            hideTitle: false,
            cols: 1,
            cells: [
              {
                label: '红单',
                number: '1',
                balls: ['01', '07', '13', '19', '23', '29', '35', '45'],
                name: 'HB_RODD'
              },
              {
                label: '红双',
                number: '2',
                balls: ['02', '08', '12', '18', '24', '30', '34', '40', '46'],
                name: 'HB_REVEN'
              },
              {
                label: '红大',
                number: '3',
                balls: ['29', '30', '34', '35', '40', '45', '46'],
                name: 'HB_ROVER'
              },
              {
                label: '红小',
                number: '4',
                balls: ['01', '02', '07', '08', '12', '13', '18', '19', '23', '24'],
                name: 'HB_RUNDER'
              },
              {
                label: '绿单',
                number: '5',
                balls: ['05', '11', '17', '21', '27', '33', '39', '43'],
                name: 'HB_GODD'
              },
              {
                label: '绿双',
                number: '6',
                // balls: ['06', '17', '22', '28', '32', '38', '44'],
                balls: ['06', '16', '22', '28', '32', '38', '44'],
                name: 'HB_GEVEN'
              },
              {
                label: '绿大',
                number: '7',
                balls: ['27', '28', '32', '33', '38', '39', '43', '44'],
                name: 'HB_GOVER'
              },
              {
                label: '绿小',
                number: '8',
                balls: ['05', '06', '11', '16', '17', '21', '22'],
                name: 'HB_GUNDER'
              },
              {
                label: '蓝单',
                number: '9',
                balls: ['03', '09', '15', '25', '31', '37', '41', '47'],
                name: 'HB_BODD'
              },
              {
                label: '蓝双',
                number: '10',
                balls: ['04', '10', '14', '20', '26', '36', '42', '48'],
                name: 'HB_BEVEN'
              },
              {
                label: '蓝大',
                number: '11',
                balls: ['25', '26', '31', '36', '37', '41', '42', '47', '48'],
                name: 'HB_BOVER'
              },
              {
                label: '蓝小',
                number: '12',
                balls: ['03', '04', '09', '10', '14', '15', '20'],
                name: 'HB_BUNDER'
              }
            ]
          }]
        },
        {
          name: '半半波',
          type: 'SB3',
          items: [{
            type: 'normal_grid',
            title: [
              {name: '半半波', type: 'label', width: '20%'},
              {name: '赔率', type: 'odds', width: '20%'},
              {name: '金额', type: 'money', width: '25%'},
              {name: '号码', type: 'balls', width: '35%'},
            ],
            hideTitle: false,
            cols: 1,
            cells: [
              {
                label: '红大单',
                number: '1',
                balls: ['29', '35', '45'],
                name: 'HH_ROO'
              },
              {
                label: '红大双',
                number: '2',
                balls: ['30', '34', '40', '46'],
                name: 'HH_ROE'
              },
              {
                label: '红小单',
                number: '3',
                balls: ['01', '07', '13', '19', '23'],
                name: 'HH_RUO'
              },
              {
                label: '红小双',
                number: '4',
                balls: ['02', '08', '12', '18', '24'],
                name: 'HH_RUE'
              },
              {
                label: '绿大单',
                number: '5',
                balls: ['27', '33', '39', '43'],
                name: 'HH_GOO'
              },
              {
                label: '绿大双',
                number: '6',
                balls: ['28', '32', '38', '44'],
                name: 'HH_GOE'
              },
              {
                label: '绿小单',
                number: '7',
                // balls: ['05', '11', '17', '21', '38', '39', '43', '44'],
                balls: ['05', '11', '17', '21'],
                name: 'HH_GUO'
              },
              {
                label: '绿小双',
                number: '8',
                balls: ['06', '16', '22'],
                name: 'HH_GUE'
              },
              {
                label: '蓝大单',
                number: '9',
                balls: ['25', '31', '37', '41', '47'],
                name: 'HH_BOO'
              },
              {
                label: '蓝大双',
                number: '10',
                balls: ['26', '36', '42', '48'],
                name: 'HH_BOE'
              },
              {
                label: '蓝小单',
                number: '11',
                balls: ['03', '09', '15'],
                name: 'HH_BUO'
              },
              {
                label: '蓝小双',
                number: '12',
                balls: ['04','10', '14', '20'],
                name: 'HH_BUE'
              }
            ]
          }]
        },
        {
          name: '七色波',
          type: 'SB4',
          items: [{
            type: 'normal_grid',
            title: [
              {name: '号码', type: 'label', width: '25%'},
              {name: '赔率', type: 'odds', width: '25%'},
              {name: '金额', type: 'money', width: '50%'}
            ],
            hideTitle: false,
            cols: 4,
            cells: [
              {label: '红波', number: '1', name: 'C7_R'},
              {label: '蓝波', number: '2', name: 'C7_B'},
              {label: '绿波', number: '3', name: 'C7_G'},
              {label: '和局', number: '4', name: 'C7_N'}
            ]
          }]
        },
    ]

  },
  {
    name: '尾数',
    quickBet: false,
    id: 54,
    tabs: [
      {
        name: '头尾数',
        type: 'TWS',
        quickBet: false,
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '号码', type: 'label', width: '25%'},
              {name: '赔率', type: 'odds', width: '25%'},
              {name: '金额', type: 'money', width: '50%'}
            ],
            hideTitle: true,
            mainTitle: '特码头尾数',
            cols: 5,
            cells: [
              {label: '头0', number: '1', name: 'SH0'},
              {label: '头1', number: '2', name: 'SH1'},
              {label: '头2', number: '3', name: 'SH2'},
              {label: '头3', number: '4', name: 'SH3'},
              {label: '头4', number: '5', name: 'SH4'},
              {label: '尾0', number: '6', name: 'SF0'},
              {label: '尾1', number: '7', name: 'SF1'},
              {label: '尾2', number: '8', name: 'SF2'},
              {label: '尾3', number: '9', name: 'SF3'},
              {label: '尾4', number: '10', name: 'SF4'},
              {label: '尾5', number: '11', name: 'SF5'},
              {label: '尾6', number: '12', name: 'SF6'},
              {label: '尾7', number: '13', name: 'SF7'},
              {label: '尾8', number: '14', name: 'SF8'},
              {label: '尾9', number: '15', name: 'SF9'}
            ]
          }
        ]
      },
      {
        name: '正特尾数',
        type: 'ZTWS',
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '号码', type: 'label', width: '25%'},
              {name: '赔率', type: 'odds', width: '25%'},
              {name: '金额', type: 'money', width: '50%'}
            ],
            hideTitle: true,
            mainTitle: '正特尾数',
            cols: 2,
            cells: [
              {label: '尾0', number: '1', name: 'NF0'},
              {label: '尾1', number: '2', name: 'NF1'},
              {label: '尾2', number: '3', name: 'NF2'},
              {label: '尾3', number: '4', name: 'NF3'},
              {label: '尾4', number: '5', name: 'NF4'},
              {label: '尾5', number: '6', name: 'NF5'},
              {label: '尾6', number: '7', name: 'NF6'},
              {label: '尾7', number: '8', name: 'NF7'},
              {label: '尾8', number: '9', name: 'NF8'},
              {label: '尾9', number: '10', name: 'NF9'}
            ]
          }
        ]
      },
    ]

  },
  {
    name: '七码五行',
    quickBet: false,
    id: 55,
    tabs: [
      {
        name: '七码',
        type: 'QM',
        quickBet: false,
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '七码', type: 'label', width: '35%'},
              {name: '赔率', type: 'odds', width: '30%'},
              {name: '金额', type: 'money', width: '35%'}
            ],
            hideTitle: false,
            cols: 2,
            cells: [
              {label: '单0 . 双7', number: '1', name: 'S7_0O7E'},
              {label: '大0 . 小7', number: '9', name: 'S7_0O7U'},
              {label: '单1 . 双6', number: '2', name: 'S7_1O6E'},
              {label: '大1 . 小6', number: '10', name: 'S7_1O6U'},
              {label: '单2 . 双5', number: '3', name: 'S7_2O5E'},
              {label: '大2 . 小5', number: '11', name: 'S7_2O5U'},
              {label: '单3 . 双4', number: '4', name: 'S7_3O4E'},
              {label: '大3 . 小4', number: '12', name: 'S7_3O4U'},
              {label: '单4 . 双3', number: '5', name: 'S7_4O3E'},
              {label: '大4 . 小3', number: '13', name: 'S7_4O3U'},
              {label: '单5 . 双2', number: '6', name: 'S7_5O2E'},
              {label: '大5 . 小2', number: '14', name: 'S7_5O2U'},
              {label: '单6 . 双1', number: '7', name: 'S7_6O1E'},
              {label: '大6 . 小1', number: '15', name: 'S7_6O1U'},
              {label: '单7 . 双0', number: '8', name: 'S7_7O0E'},
              {label: '大7 . 小0', number: '16', name: 'S7_7O0U'}
            ]
          }
        ]
      },
      {
        name: '五行',
        type: 'WH',
        items: [
          {
            type: 'normal_grid',
            title: [
              {name: '五行', type: 'label', width: '15%'},
              {name: '号码', type: 'wx', width: '50%'},
              {name: '赔率', type: 'odds', width: '15%'},
              {name: '金额', type: 'money', width: '30%'}
            ],
            hideTitle: false,
            cols: 1,
            cells: [
              {
                label: '金',
                number: '1',
                wx: '09, 21, 33, 45',
                name: 'F_METAL'
              },
              {
                label: '木',
                number: '2',
                wx: '09, 21, 33, 45',
                name: 'F_WOOD'
              },
              {
                label: '水',
                number: '3',
                wx: '09, 21, 33, 45',
                name: 'F_WATER'
              },
              {
                label: '火',
                number: '4',
                wx: '09, 21, 33, 45',
                name: 'F_FIRE'
              },
              {
                label: '土',
                number: '5',
                wx: '09, 21, 33, 45',
                name: 'F_EARTH'
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: '中一',
    quickBet: false,
    id: 56,
    type: 'zhongyi',
    tabs: [
      {
        name: '五中一',
        type: 'IN15',
        defaultSelected: true,
        quickBet: false,
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '六中一',
        type: 'IN16',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '七中一',
        type: 'IN17',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '八中一',
        type: 'IN18',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '九中一',
        type: 'IN19',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      },
      {
        name: '十中一',
        type: 'IN1A',
        items: [{
          type: 'normal_grid',
          title: [
            {name: '号码', type: 'number', width: '50%'},
            {name: '勾选', type: 'checkbox', width: '50%'}
          ],
          hideTitle: false,
          cols: 5,
          cells: [
            {number: '01'},
            {number: '11'},
            {number: '21'},
            {number: '31'},
            {number: '41'},
            {number: '02'},
            {number: '12'},
            {number: '22'},
            {number: '32'},
            {number: '42'},
            {number: '03'},
            {number: '13'},
            {number: '23'},
            {number: '33'},
            {number: '43'},
            {number: '04'},
            {number: '14'},
            {number: '24'},
            {number: '34'},
            {number: '44'},
            {number: '05'},
            {number: '15'},
            {number: '25'},
            {number: '35'},
            {number: '45'},
            {number: '06'},
            {number: '16'},
            {number: '26'},
            {number: '36'},
            {number: '46'},
            {number: '07'},
            {number: '17'},
            {number: '27'},
            {number: '37'},
            {number: '47'},
            {number: '08'},
            {number: '18'},
            {number: '28'},
            {number: '38'},
            {number: '48'},
            {number: '09'},
            {number: '19'},
            {number: '29'},
            {number: '39'},
            {number: '49'},
            {number: '10'},
            {number: '20'},
            {number: '30'},
            {number: '40'},
            {number: ''}
          ]
        }]
      }
    ]
  }
]


export default layoutNew;
